### ISSUE TITLE
feature request: `dip build` command

### ISSUE THREAD

**Issue by omarsotillo** [bibendi/dip#102]
Hello 👋

Tried running `dip build`  thinking it will directly do a docker-compose build command. 

There is the possibility to do it through `dip compose build` but `dip build` was a natural step for me to do after seeing that many commands on the first level of semantic hirarchy are already docker related [up, down, stop]

just started using your tool as a replacement for make :) really cool 😄 

I could try to implement it if you think is worth the investment and sharing :D

**Comment by bibendi** [comment]
Hi!

Good idea! 

> I could try to implement

If you have time to do this, you are welcome!

**Comment by omarsotillo** [comment]
Perfect! I take over here 🤝

One question @bibendi 
Would you say it makes sense to support this command also from `ssh` and `nginx` top-level commands?

If yes, I will continue with the following feature-plan:
- [ ] PR supporting `dip build [OPTIONS]`
- [ ] PR supporting `dip ssh build [OPTIONS]`
- [ ] PR supporting `dip nginx build [OPTIONS]`

**Comment by bibendi** [comment]
> to support this command also from ssh and nginx top-level commands

I think this makes no sense because ssh and nginx images cannot be built. They aren't part of a project's Docker Compose config.

**Comment by omarsotillo** [comment]
> ssh and nginx images cannot be built

Just took a look at the documentation for `ssh-agent` and `nginx-proxy` -> my knowledge was limited and had the wrong assumptions. Thanks for the clarification 👍

**Comment by omarsotillo** [comment]
This was implemented in #104
