### ISSUE TITLE
Question: Are you able to interpolate env variables or command in compose_run_options?

### ISSUE THREAD

**Issue by butsjoh** [bibendi/dip#119]
Hi,

Was wondering if it would be possible to interpolate $(pwd), ${DIP_WORK_DIR_REL_PATH} or other env, commands inside compose_run_options. Below an example why that would be useful:

We have scripts that we need to run for our dev env that developers don't really need to understand (other members of the team not knowledgeable about the tech). One example here is that we need to add a script to a container temporarily (not defined as a volume in the docker-compose) for the duration of the script. We can use the -v (https://docs.docker.com/compose/reference/run/) for mounting a volume with docker-compose but that only works if you give it an absolute path. It cannot work with relatives paths and we are trying todo the following.

truncate for clarity
```
  vault_setup:
    description: Setup the vault
    service: vault
    command: /bin/sh
    compose_run_options:
      [
        no-deps,
        use-aliases,
        "-e VAULT_ADDR=https://host.docker.internal:8200",
        "-e VAULT_SKIP_VERIFY=true",
        "-v ${DIP_WORK_DIR_REL_PATH}/vault/init.file:/vault/init.file:ro"
     ]
```

what does work if we provide it the full path: (but that is hard to spread across the team cause those paths are not going to be the same)

```
  vault_setup:
    description: Setup the vault
    service: vault
    command: /bin/sh
    compose_run_options:
      [
        no-deps,
        use-aliases,
        "-e VAULT_ADDR=https://host.docker.internal:8200",
        "-e VAULT_SKIP_VERIFY=true",
        "-v /Users/some_path/vault/init.file:/vault/init.file:ro"
      ]
```

So is there a way that you think off that would allow use to interpolate something in the run_options?

**Comment by bibendi** [comment]
Hi,

I somehow thought that it was already implemented, but I see now in the sources that it was missing.

No problem will fix that in the next release.

**Comment by bibendi** [comment]
#120
