### ISSUE TITLE
coveralls.io leaks your information

### ISSUE THREAD

**Issue by aviaoh** [bibendi/dip#14]
hi @bibendi ,
I recently saw your commits in my coveralls.io account:
![image](https://cloud.githubusercontent.com/assets/22256371/21893720/f4438d26-d8e4-11e6-965e-eb7b3630dd0f.png)

I also opened issue: https://github.com/lemurheavy/coveralls-public/issues/909
FYI.

**Comment by artofhuman** [comment]
@aviaoh i don't think this issue for this repo. It should be open in coveralls.

**Comment by aviaoh** [comment]
@artofhuman as I wrote in the description, iI also opened an issue for coveralls.
This issue is only for you let know (as i cant send you email or something like that....)
