### ISSUE TITLE
port forwardings in docker-compose.yml are not activated via dip

### ISSUE THREAD

**Issue by hachi8833** [bibendi/dip#142]
**Describe the bug**

I found the following difference in the behaviors between docker-compose and dip.

- 1: normal docker-compose command:
   - PORTS: `0.0.0.0:3000->3000/tcp, 0.0.0.0:9229->9229/tcp`
- 2: dip command
  - PORTS: (empty)

**To Reproduce**
1.  Check https://github.com/hachi8833/dip_issue and README to reproduce the issue

**Expected behavior**

I expect that dip activates the port forwarding configs in docker-compose.yml.
I need to specify the explicit `HOST` env as `0.0.0.0` to expose the port for nuxt-app, but this can't be used via dip.

**Screenshots**

![image](https://user-images.githubusercontent.com/4289625/144737617-82053391-88d1-4bd4-a840-e595e1ab5288.png)

![image](https://user-images.githubusercontent.com/4289625/144737753-f5ff4fe6-68d8-4cce-8eec-fc52c18aba3c.png)

**Context (please complete the following information):**
 - OS: macOS Big Sur (11.6)
 - Docker Desktop 4.2.0 (70708) 
 - dip: 7.2.0
 - Ruby: ruby 3.0.3p157

(I'm wondering if I took a mistake or something...)

Best regards,

**Comment by bibendi** [comment]
Hi!
Dip executes commands through `docker compose run` so that you need to define `compose: run_options: [service-ports]` for the `sh` command if you need ports to be opened.

**Comment by hachi8833** [comment]
It works now as you suggested! Thank you very much🙏
