### ISSUE TITLE
`dip nginx` Default Image Change to `nginxproxy/nginx-proxy`

### ISSUE THREAD

**Issue by tmimura39** [bibendi/dip#144]
The default Image for `$ dip nginx` is https://github.com/bibendi/nginx-proxy
https://github.com/bibendi/dip/blob/9eb5faf55fe6ba581f936a93ac4c7941017f90b4/lib/dip/cli/nginx.rb#L22

But, this Image has not been maintained for a long time!

Currently, using this Image generates a malformed /etc/nginx/conf.d/default.conf and `nginx -s reload` fails.
We have not been able to determine the cause of the failure, but have confirmed that using the original Image, https://github.com/nginx-proxy/nginx-proxy, eliminates this problem.

Since https://github.com/nginx-proxy/nginx-proxy seems to be actively maintained, why not change it to use this Image by default?

I am aware that it is possible to change the Image used with the `--image` option, but I am hoping to change the default Image as I have had difficulty identifying where the problem is originating.

**Comment by bibendi** [comment]
Hi!
I used the fork because the original image did not support VIRTUAL_PATH environment variable.
As I see, the original image supports it now, so we can switch the image.
