### ISSUE TITLE
Question: Is it possible to use Docker Compose profiles?

### ISSUE THREAD

**Issue by nilcolor** [bibendi/dip#157]
There is a handy feature in Docker Compose called "profiles" https://docs.docker.com/compose/profiles/
I tried to use it with `dip` using combinations of `method`/`run_options` but still cannot use profiles. If I understand the code correctly, this is not possible at the moment. Is that correct? Are there any plans to support profiles? I can try to do a PR to support them.

**Comment by bibendi** [comment]
Hi @nilcolor,
I was also thinking about this feature a few weeks ago. We need to add `:profiles` to the compose command hash and slightly refactor this file https://github.com/bibendi/dip/blob/21885c932653faa068b543e47c6bfcbba172ecbf/lib/dip/commands/runners/docker_compose_runner.rb#L21

It is on my schedule on this year :)
If you cannot wait, you can implement the feature.

**Comment by nilcolor** [comment]
I was thinking along these lines as well. I'll try to suggest a PR in the near future.

**Comment by nilcolor** [comment]
@bibendi thanks for the quick response and rolling out v7.6.0!
