### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/bdw-gc/lib/libgc.1.dylib

### ISSUE THREAD

**Issue by dawidof** [bibendi/dip#33]
Could not make dip working. Reinstall via brew `crystal`, `crystal-lang`, `glib`, `bdw-gc`, `libevent`, `libyaml`, `dyld-headers`, nothing helps, xcode command line installed and accepted. I've got High Sierra 10.13.2 (17C205).
Tried to find solution, none is working.
Please help!

![screen shot 2018-01-26 at 21 44 32](https://user-images.githubusercontent.com/1425756/35459858-294ad308-02e2-11e8-88fc-ccbb85f5ecd8.png)

**Comment by DmitryBochkarev** [comment]
I believe you need to upgrade to crystal 1.24 https://github.com/bibendi/dip/pull/32

**Comment by dawidof** [comment]
I've got 0.24.1

**Comment by dawidof** [comment]
@DmitryBochkarev But thanks, I've found the problem
Just `brew upgrade bdw-gc`
![screen shot 2018-01-27 at 11 45 04](https://user-images.githubusercontent.com/1425756/35471268-093581aa-0358-11e8-9586-966d412f1489.png)

**Comment by dawidof** [comment]
I know many people have such problem. Maybe its good to add to a readme file, as troubleshooting

**Comment by bibendi** [comment]
As far as I can see the problem does not belong directly to dip. And there is no need to add this to the readme. You simply had a broken one of the crystal dependency. 
Anyway everything is perfectly searched in closed issues.
Thanks for the solution.
