### ISSUE TITLE
run dip with variables

### ISSUE THREAD

**Issue by Neznauy** [bibendi/dip#63]
Hello,
can I pass variables to dip manually not in interactive mode?
For example, I would like to run ```rake db:migrate``` in different environments. So, I made
``` 
docker-compose.yml
services:
  web:
    environment:
      -HANAMI_ENV=${ENV}
```
and
```
dip.yml
environment:
  ENV: ${ENV}
```
And then I tried ```dip ENV=test bundle exec rake db:migrate```, but dip don't accept variable.
Also, as I understand, you make anything like this in https://github.com/bibendi/dip#dip-run

dip version: 3.8.2, binary; Ubuntu 18.04

**Comment by bibendi** [comment]
Hey!

Thanks for reporting!

It looks there is a regression. I've just checked that, and passing environment variables is broken in basic mode, but work fine when you integrate dip into the shell.

works for me:

```
FOO=bar bash -c env | grep FOO
```

doesn't work

```
dip FOO=bar bash -c env | grep FOO
```

I'll address this in a couple of days.
