### ISSUE TITLE
Do not show other container names when running command

### ISSUE THREAD

**Issue by vitobotta** [bibendi/dip#70]
Hi! I am loving this utility, it makes it easier to work with Docker. I have a quick question: can I somehow hide / remove the "Starting X" messages when running a command, so it looks like that command is not from docker compose/dip? Thanks!

**Comment by bibendi** [comment]
Hey!
It is my pain too!
This error comes from https://github.com/docker/compose/issues/6026
It would be great if you vote at that issue ;)

**Comment by vitobotta** [comment]
aha so it's not just me :) Thanks
