### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by AlexeyMatskevich** [bibendi/dip#71]
I tried to install precompiled binary in Arch Linux system:
What i did: 
```
❯ sudo su                                                                                                           
alexey-pc# curl -L https://github.com/bibendi/dip/releases/download/3.8.3/dip-`uname -s`-`uname -m` > /usr/local/bin/dip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0      7      0 --:--:--  0:00:01 --:--:--     7
alexey-pc# exit
❯ sudo chmod +x /usr/local/bin/dip
```
What I have:
```
❯ dip --help
/usr/local/bin/dip: line 1: Not: command not found
```
Could I do something wrong?

**Comment by bibendi** [comment]
Hi.
Can you get a size of downloaded binary? I bet that it wasn't correctly downloaded. Also, please show your `uname -sm`.

**Comment by AlexeyMatskevich** [comment]
Hi, thanks for your answer!
```
❯ uname -sm
Linux x86_64
❯ sudo du -sh /usr/local/bin/dip 
4,0K    /usr/local/bin/dip
```

**Comment by bibendi** [comment]
The size should be 33 Mb. It looks like something went wrong with your "curl" command. Please, try to download it manually at this page https://github.com/bibendi/dip/releases/tag/v3.8.3
Also, you can use [Homebrew for Linux](https://github.com/bibendi/dip#homebrew) to make sure you Dip is always up to date.
