### ISSUE TITLE
Run command in existing container

### ISSUE THREAD

**Issue by vitobotta** [bibendi/dip#72]
Hi, I have defined a `rails` dip command so to run tests with an environment configured with docker-compose. However it starts a new container each time, so startup is slow. How can I use an existing container if I run `docker-compose up` beforehand? Compose starts the container with name `app-test`, but dip starts a new container named `app-rails` with the name of the command in it. I tried setting `container_name: app-test` in the dip command but nothing changes. Thanks in advance

**Comment by bibendi** [comment]
Hi!

>  it starts a new container each time, so startup is slow. How can I use an existing container if I run docker-compose up beforehand?

You can't reuse it. This architecture is by design. The startup can't be slow, because the overhead of starting a new container tends to zero.

You can find good working examples at:
- https://github.com/evilmartians/terraforming-rails/tree/master/examples/dockerdev
- https://github.com/bibendi/dip-example-rails

**Comment by vitobotta** [comment]
Hi @bibendi, it's weird but if I run tests from inside the existing container it's a bit faster than if I run them through the dip command (my config is correct). Could it be because on Mac Docker uses a virtual machine behind the scenes? Thanks

**Comment by bibendi** [comment]
Probably yes.

I have that numbers on my Linux machine:

```
$ time dip run bash -c exit

0,76s user 0,10s system
```

Overhead is only about 0,76s, so it is no bother me.

**Comment by vitobotta** [comment]
Uhm. I ran that command and I get 

`dip run bash -c exit  0.55s user 0.15s system 31% cpu 2.194 total`

so it's not bad I guess. Perhaps I am complaining too much 🗡 

Thanks!

**Comment by jgarber-cisco** [comment]
I've also run into this (on an M3 Mac in 2025 with Docker VMM 🌬️). I trust @bibendi's judgement on the architecture. Things to check if your container startup is slow and you can't blame it on the system:

- Specifying forced rebuilding in docker-compose.yml. Mine had `pull_policy: build` for some reason and while it used cached layers every time, it still added a couple seconds.
- Time-consuming activities in an entrypoint script. My `entrypoint.sh` had some too-clever waits that added 4 seconds to container startup.

One is able to add `method: exec` to the interaction as shown in the [example.yml](https://github.com/bibendi/dip/blob/b127ce8ae1d501ec92c4972728567b8d4d4d3b7f/examples/dip.yml#L31), but with the above tweaking I got it down to 1.5 sec starting a new container, which is quick enough for me!
