### ISSUE TITLE
Run/exec performance

### ISSUE THREAD

**Issue by nomasprime** [bibendi/dip#81]
Thanks for Dip. Saved me having to customise various plug-ins to wrap Docker Compose commands.

Does Dip run a new container each time? If so, is it possible to run a new container if doesn't exist and then exec afterwards to boost performance?

**Comment by bibendi** [comment]
Hi!
Yes, DIP starts a new container every time.
I don't have any plans to change this behavior in the near future.
I've discussed that in this issue https://github.com/bibendi/dip/issues/72

**Comment by nomasprime** [comment]
Ah, I'm on Mac so it's an issue for me too. Generally Docker on Mac's an issue though.

I'm currently exploring a hybrid native/Docker approach, maybe that's the best solution.

**Comment by yano3nora** [comment]
@nomasprime 

It looks like the existing container built with `dip up` is used with `compose_method: exec`.

I don't know if this works according to your expectations ...

**Comment by nomasprime** [comment]
Thanks @yano3nora.

I'm not really using Docker on Mac anymore, not until performance improves anyway.
