### ISSUE TITLE
Environment variables from .env not loaded when using dip in a sub-directory

### ISSUE THREAD

**Issue by baptvlmr** [bibendi/dip#86]
This is more a question than a bug report.

I am using DIP version 5.0.0 with the precompiled binary on Linux x86_64.
I have the following project :
```
dip/
├── subdir/
├── .env
├── dip.yml
└── docker-compose.yml
```

```dosini
#.env
TAG=latest
```

```yaml
# docker-compose.yml
version: '3.7'

services:

  alpine:
    image: alpine:$TAG

```

```yaml
# dip.yml
version: '5.0.0'

interaction:
  test:
    service: alpine
    command: echo 'test succeeded'
```

When I use `dip` from the root directory (where `docker-compose.yml` and `dip.yml` files are located) this is works as expected, but I when I use it from `subdir/` I get the following error :

```shell
$ dip test
WARNING: The TAG variable is not set. Defaulting to a blank string.
ERROR: no such image: alpine:: invalid reference format
```

I know this is the [default behaviour of `docker-compose`](https://docs.docker.com/compose/env-file/) which looks for a `.env` file only in the current working directory. But as a CLI tool, I want to use `dip` in various sub-directories.

Is there any way to do this ? Am I doing something wrong ?

**Comment by bibendi** [comment]
Hi!
Hmm, interesting, I've never used that Compose behavior. I need some time to get to know it. I'll try to look on it this week.

**Comment by baptvlmr** [comment]
Hey ! Thanks for your reply :slightly_smiling_face: 

One possible approach to have environment variables loaded when using `dip` from a sub-directory would be the `--project-directory` option.
It could be set to the directory path of the `docker-compose.yml` and `dip.yml` files ?

For example, this is what happens when I am in my `subdir/` directory : 

```console
baptvlmr@machina:~/dip $ docker-compose --project-directory=.. run alpine echo 'success'
success
baptvlmr@machina:~/dip $ docker-compose run alpine echo 'success'
WARNING: The TAG variable is not set. Defaulting to a blank string.
ERROR: no such image: alpine:: invalid reference format
```

**Comment by bibendi** [comment]
Please try Dip v6.0.0 where you can define project_directory key in dip.yml config.
