### ISSUE TITLE
compose_run_options: [rm] ???

### ISSUE THREAD

**Issue by LimeBlast** [bibendi/dip#88]
Is it possible to have containers started via dip, remove themselves once they're finished with?

If I understand docker(-compose) well enough, then I'm thinking something like the `--rm` flag.

I guessed it might be possible to configure via the `dip.yml` file, something like:

```
compose_run_options: [rm]
```

But this doesn't work

Thanks.

**Comment by bibendi** [comment]
Hi!

You have described the behavior that Dip is using by default. You don't need to do anything to achieve this.

You can inspect commands that Dip is sending to Docker Compose by writing something like below:

```sh
DIP_ENV=debug dip <cmd>
```

**Comment by LimeBlast** [comment]
So it is, my apologies. I think it was RubyMine spinning up all the extra containers, and I assumed it was dip.

I know this is a bit off topic (so I'm happy to close this ticket). but have you had much luck running dip commands with/via RubyMine?

Thanks.

**Comment by bibendi** [comment]
I've been coding with RubyMine for a while, but I prefer using the console to run application's commands. I just set up a remote interpreter to allow RubyMine downloading gems from Docker.

**Comment by LimeBlast** [comment]
That sounds pretty similar to what I've been doing, and it seems to work fairly well - although I've not figured out how to get debugging to work.

In any case, thank you for your help :)

**Comment by bibendi** [comment]
I don't use RubyMine's debugger as well :) 
I just type `binding.pry` in a code file and start an application.
