### ISSUE TITLE
how to use SSH command line

### ISSUE THREAD

**Issue by jnicho02** [bibendi/dip#95]
Sorry, being a bit of a dumb user here. Could you explain whether/how I can use SSH commands from within dip shell?

background: I use dip to manage a number of Rails sites all with slightly different hosting (not by me, I inherited them!). For each site I have a 'livepull' command that does a postgres dump of the production db, downloads it, and restores into a dev db for investigating problems. This plays nicely with Heroku. For some sites, I have a .sh file to SSH in and issue a pg_dump command, then SFTP the file locally, and run a pg_restore.

Can I run "SSH xyz@123.123.123.123 << EOF pg_dump ....., exit EOF" in dip shell? If I do a 'dip ssh up' first?

**Comment by bibendi** [comment]
Hi Jez!
It seems that I didn't understand your question enough. Please, provide your configs (dip.yml, docker-compose.yml).

dip ssh it's a shourtcut command to run a sidekick container with running ssh-agent which shares SSH_AUTH_SOCK to your main container.

**Comment by jnicho02** [comment]
I'll try to explain what I want to achieve 👍 

- I have a remote Production server that I can ssh into
- I have run ssh-add, so that is uses my credentials to login
- I ssh (and sftp) into the server to dump the Production database, copy the dump file to my local machine, and restore the dump to my dev database
- I wish to do this from within my Docker container (ruby:2.6.6-slim-buster) which does not currently have an 'ssh' command

dip.yml includes the interaction:
```sh
interacton:
  livepull:
    description: Pull data from live into development
    service: runner
    command: /bin/bash local_restore.sh
```
local_restore.sh has the lines:
```sh
ssh myuser@999.99.99.999 <<EOF
  pg_dump postgres://pg_user:pg_password@localhost:5432/mydb -h localhost --no-acl --no-owner -Fc > mydb_production_$(date +'%Y%m%d').dump
  exit
EOF
sftp myuser@999.99.99.999 <<EOF
  get my_db_production_$(date +'%Y%m%d').dump
  exit
EOF
dropdb -h postgres -U postgres my_db_development
createdb -h postgres -U postgres my_db_development
pg_restore -h postgres -U postgres -d my_db_development my_db_production_$(date +'%Y%m%d').dump
```

Perhaps the SSH that dip has is nothing to do with what I am trying to do? Does 'dip ssh' make it so that you can ssh **in** to your Docker instance, not **out from**?

Do you have any pointers? Just install openssh-client?

**Comment by jnicho02** [comment]
Heh! Typically, i've just answered my own question.

I added openssh-client to my Dockerfile, and '- ~/.ssh:/root/.ssh:ro' to my volumes. I know that it is not ideal to share my .ssh like this, but the Docker images are not going to be published.

Thanks for listening. Dip has been very helpful in my bid to manage chaos and work almost 100% in Docker, keep up the good work.

**Comment by blijblijblij** [comment]
fyi @jnicho02 

alternatively one could do without ssh altogether and lean on the [build in postgres container behaviou](https://github.com/docker-library/docs/blob/master/postgres/README.md#initialization-scripts)r, from their docs

> Initialization scripts

> If you would like to do additional initialization in an image derived from this one, add one or more *.sql, *.sql.gz, or *.sh scripts under /docker-entrypoint-initdb.d (creating the directory if necessary). After the entrypoint calls initdb to create the default postgres user and database, it will run any *.sql files, run any executable *.sh scripts, and source any non-executable *.sh scripts found in that directory to do further initialization before starting the service.

> Warning: scripts in /docker-entrypoint-initdb.d are only run if you start the container with a data directory that is empty; any pre-existing database will be left untouched on container startup. One common problem is that if one of your /docker-entrypoint-initdb.d scripts fails (which will cause the entrypoint script to exit) and your orchestrator restarts the container with the already initialized data directory, it will not continue on with your scripts.

> For example, to add an additional user and database, add the following to /docker-entrypoint-initdb.d/init-user-db.sh:

```
#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER docker;
    CREATE DATABASE docker;
    GRANT ALL PRIVILEGES ON DATABASE docker TO docker;
EOSQL
```
